baseurl: 
permalink: /:year/:month/:day/:title/
sass: 
  style: compressed
plugins: 
  - jekyll-paginate
  - jekyll-feed
paginate: 20
paginate_path: "/page:num/"
excerpt_separator: <!--more-->
highlighter: rouge